/**
 * The forge: the organisation that holds every gateway's repository, the two teams a person may
 * belong to in it, a gateway's own repository, and the key it reads that repository with. Shared
 * because the names must agree between `enroll-gateway`, `forge-membership` and the dashboard's
 * link.
 *
 * The machine account owns an organisation, creates each gateway's repository in it, and
 * `forge-membership` places each login in the team its Postgres role maps to; it is not a site
 * administrator. Both teams have write; `main` is protected on every gateway repository with pushes
 * disabled and one approval required from `administrators`, which is where gitops:manage is
 * enforced inside the forge. A repository created before the organisation existed is transferred in
 * on re-enrolment, not recreated.
 *
 * The private key is never seen here: the appliance generates its keypair in bootstrap.mjs and
 * sends the public half, registered read-only so an appliance cannot author the flow it will be
 * asked to deploy.
 *
 * Failure here is non-fatal: by the time this runs the token is spent and the broker credential
 * exists, and telemetry needs nothing from the forge. A failure is logged loudly, `repository`
 * comes back null, and the response says so.
 */

export interface ForgeConfig {
  baseUrl: string;
  user: string;
  password: string;
  /** Where Gitea delivers a push (forge-events), and the secret it signs with. Empty: no hook. */
  webhookUrl: string;
  webhookSecret: string;
}

export interface ForgeRepository {
  full_name: string;
  ssh_url: string;
  default_branch: string;
}

/**
 * The organisation every gateway repository lives in, and the two teams in it. Named here and in
 * frontend/src/constants.js, and the two must agree. Lower-case because it is a URL segment.
 */
export const FORGE_ORGANISATION = "gateways";
export const FORGE_TEAMS = {
  Administrator: "administrators",
  Shopfloor_Manager: "managers",
} as const;
export type ForgeTeamRole = keyof typeof FORGE_TEAMS;

/**
 * The forge's configuration, or null when this deployment has none. All three or nothing: a
 * half-configured forge would answer 401 on every enrolment, so it is reported here.
 */
export function forgeConfig(): ForgeConfig | null {
  const baseUrl = (Deno.env.get("GITEA_INTERNAL_URL") ?? "").replace(/\/+$/, "");
  const user = Deno.env.get("GITEA_MACHINE_USER") ?? "";
  const password = Deno.env.get("GITEA_MACHINE_PASSWORD") ?? "";

  if (!baseUrl && !user && !password) return null;

  if (!baseUrl || !user || !password) {
    const missing = [
      !baseUrl && "GITEA_INTERNAL_URL",
      !user && "GITEA_MACHINE_USER",
      !password && "GITEA_MACHINE_PASSWORD",
    ].filter(Boolean).join(", ");
    console.error(
      `the forge is half-configured (${missing} unset), so gateway repositories are DISABLED. ` +
        "Set all three or none -- a partially configured forge answers 401 on every enrolment.",
    );
    return null;
  }

  // Optional, unlike the three above: a forge without a webhook is one the dashboard learns about
  // one tick late. Both or neither, and enrolment logs which.
  const webhookUrl = (Deno.env.get("GITEA_WEBHOOK_URL") ?? "").trim();
  const webhookSecret = Deno.env.get("GITEA_WEBHOOK_SECRET") ?? "";
  if (!!webhookUrl !== !!webhookSecret) {
    console.warn(
      `the forge's webhook is half-configured (${webhookUrl ? "GITEA_WEBHOOK_SECRET" : "GITEA_WEBHOOK_URL"} unset); ` +
        "no hook will be registered on gateway repositories until both are set",
    );
  }
  const webhook = webhookUrl && webhookSecret ? { webhookUrl, webhookSecret } : { webhookUrl: "", webhookSecret: "" };

  return { baseUrl, user, password, ...webhook };
}

/**
 * The repository name for a gateway, derived from the `sparkplug_id` rather than stored: the id is
 * generated by the database and cannot disagree with the gateway.
 */
export function repositoryNameFor(sparkplugId: string): string {
  return `gateway-${sparkplugId}`;
}

/**
 * The public half of an OpenSSH key, or null. Shape-checked and confined to the two algorithms
 * bootstrap.mjs can generate, so this endpoint cannot write arbitrary strings into another system's
 * authorised-keys list.
 */
export function validPublicKey(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const key = value.trim();
  if (key.length > 4096) return null;
  return /^ssh-(ed25519|rsa) [A-Za-z0-9+/=]+( [^\n\r]*)?$/.test(key) ? key : null;
}

/** Basic auth as the machine account. Gitea accepts it on the API, and it needs no token exchange. */
function authHeader(cfg: ForgeConfig): string {
  return `Basic ${btoa(`${cfg.user}:${cfg.password}`)}`;
}

/** One call to the forge's API as the machine account. Shared with forge-membership. */
export async function forgeApi(
  cfg: ForgeConfig,
  method: string,
  path: string,
  body?: unknown,
): Promise<Response> {
  return await fetch(`${cfg.baseUrl}/api/v1${path}`, {
    method,
    headers: {
      Authorization: authHeader(cfg),
      ...(body === undefined ? {} : { "Content-Type": "application/json" }),
    },
    body: body === undefined ? undefined : JSON.stringify(body),
  });
}

async function refused(what: string, response: Response): Promise<Error> {
  return new Error(`${what} (${response.status}: ${(await response.text()).slice(0, 200)})`);
}

/**
 * The organisation, created if absent, and its two teams likewise. Returns the team ids by role.
 * Idempotent by inspection: a GET first, a POST only for what is missing. Private, like every
 * repository in it; `includes_all_repositories` makes a team cover every repository created later.
 * Both teams may create repositories, since a playbook repository exists before any gateway does; a
 * hand-made repository carrying a gateway's name is adopted and protected at enrolment. A found
 * team is patched if its flag disagrees.
 */
export async function ensureOrganisation(
  cfg: ForgeConfig,
): Promise<Record<ForgeTeamRole, number>> {
  const org = await forgeApi(cfg, "GET", `/orgs/${FORGE_ORGANISATION}`);
  if (org.status === 404) {
    const created = await forgeApi(cfg, "POST", "/orgs", {
      username: FORGE_ORGANISATION,
      full_name: "Gateways",
      description: "One repository per gateway. Managed by ACS-Cymru.",
      visibility: "private",
      repo_admin_change_team_access: false,
    });
    if (!created.ok) throw await refused(`could not create organisation '${FORGE_ORGANISATION}'`, created);
    console.log(`forge: created organisation '${FORGE_ORGANISATION}'`);
  } else if (!org.ok) {
    throw await refused(`could not read organisation '${FORGE_ORGANISATION}'`, org);
  }

  const listed = await forgeApi(cfg, "GET", `/orgs/${FORGE_ORGANISATION}/teams?limit=50`);
  if (!listed.ok) throw await refused("could not list the organisation's teams", listed);
  const teams = await listed.json() as { id: number; name: string; can_create_org_repo: boolean }[];

  const ids = {} as Record<ForgeTeamRole, number>;
  for (const role of Object.keys(FORGE_TEAMS) as ForgeTeamRole[]) {
    const name = FORGE_TEAMS[role];
    const existing = teams.find((t) => t.name === name);
    if (existing) {
      ids[role] = existing.id;
      if (!existing.can_create_org_repo) {
        const patched = await forgeApi(cfg, "PATCH", `/teams/${existing.id}`, { can_create_org_repo: true });
        if (!patched.ok) throw await refused(`could not let team '${name}' create repositories`, patched);
        console.log(`forge: team '${name}' may now create repositories in '${FORGE_ORGANISATION}'`);
      }
      continue;
    }
    const created = await forgeApi(cfg, "POST", `/orgs/${FORGE_ORGANISATION}/teams`, {
      name,
      description: `${role.replace("_", " ")}s of the ACS-Cymru dashboard, placed here by forge-membership.`,
      permission: "write",
      includes_all_repositories: true,
      can_create_org_repo: true,
      // No repo.projects: the unit is disabled forge-wide (DISABLED_REPO_UNITS in the Gitea env).
      units: ["repo.code", "repo.issues", "repo.pulls", "repo.releases", "repo.wiki"],
    });
    if (!created.ok) throw await refused(`could not create team '${name}'`, created);
    ids[role] = ((await created.json()) as { id: number }).id;
    console.log(`forge: created team '${name}' in '${FORGE_ORGANISATION}'`);
  }
  return ids;
}

/**
 * Create the gateway's repository in the organisation, or return the one already there,
 * transferring it in first if it was created before the organisation existed. `auto_init` matters:
 * a repository with no default branch gives the appliance nothing to clone, and git reports "remote
 * HEAD refers to a nonexistent ref".
 */
async function ensureRepository(
  cfg: ForgeConfig,
  name: string,
  gatewayName: string,
): Promise<ForgeRepository> {
  // The organisation first, then the machine account's own namespace, and only then create. A
  // repository name is unique per owner, so creating in the organisation while the legacy one
  // exists would make an empty twin and strand the history.
  const existing = await forgeApi(cfg, "GET", `/repos/${FORGE_ORGANISATION}/${name}`);
  if (existing.ok) return await existing.json() as ForgeRepository;
  if (existing.status !== 404) {
    throw await refused(`could not read repository '${name}'`, existing);
  }

  const legacy = await forgeApi(cfg, "GET", `/repos/${cfg.user}/${name}`);
  if (legacy.ok) {
    const transferred = await forgeApi(cfg, "POST", `/repos/${cfg.user}/${name}/transfer`, {
      new_owner: FORGE_ORGANISATION,
    });
    if (!transferred.ok) {
      throw await refused(`could not transfer '${cfg.user}/${name}' into '${FORGE_ORGANISATION}'`, transferred);
    }
    console.log(`forge: transferred '${cfg.user}/${name}' into '${FORGE_ORGANISATION}'`);
    return await transferred.json() as ForgeRepository;
  }
  if (legacy.status !== 404) {
    throw await refused(`could not read '${cfg.user}/${name}'`, legacy);
  }

  const created = await forgeApi(cfg, "POST", `/orgs/${FORGE_ORGANISATION}/repos`, {
    name,
    description: `Node-RED flow for gateway '${gatewayName}'. Managed by ACS-Cymru.`,
    // Belt and braces: the forge sets FORCE_PRIVATE, but the intent is stated in the request too.
    private: true,
    auto_init: true,
    default_branch: "main",
  });
  if (created.ok) return await created.json() as ForgeRepository;

  // 409 here is a race between two enrolments of one gateway, and the loser reads what the winner
  // made. A repository outlives its appliance so a re-flashed gateway gets its flow history back.
  if (created.status === 409) {
    const raced = await forgeApi(cfg, "GET", `/repos/${FORGE_ORGANISATION}/${name}`);
    if (raced.ok) return await raced.json() as ForgeRepository;
  }
  throw await refused(`could not create repository '${name}'`, created);
}

const INCIDENT_LABEL = "incident";
const INCIDENT_TEMPLATE_PATH = ".gitea/ISSUE_TEMPLATE/incident.md";

/**
 * An issue template and its label, committed to `main` in the one moment the machine account still
 * may: before the branch is protected (`enable_push: false` binds the machine account too; the
 * contents API answers 403 afterwards). Issues are the gateway's incident log. Idempotent on the
 * file and the label.
 */
async function seedIssueTemplate(cfg: ForgeConfig, name: string): Promise<void> {
  const label = await forgeApi(cfg, "POST", `/repos/${FORGE_ORGANISATION}/${name}/labels`, {
    name: INCIDENT_LABEL,
    color: "#b60205",
    description: "Something this gateway did, or failed to do, that somebody had to look at.",
  });
  // 409 and 422 are both Gitea's "that label exists".
  if (!label.ok && label.status !== 409 && label.status !== 422) {
    throw await refused(`could not create the '${INCIDENT_LABEL}' label on '${name}'`, label);
  }

  const present = await forgeApi(cfg, "GET", `/repos/${FORGE_ORGANISATION}/${name}/contents/${INCIDENT_TEMPLATE_PATH}`);
  if (present.ok) return;
  if (present.status !== 404) throw await refused(`could not read '${INCIDENT_TEMPLATE_PATH}' on '${name}'`, present);

  const template = [
    "---",
    "name: Incident",
    "about: Something this gateway did, or failed to do, that somebody had to look at",
    'title: "Incident: "',
    `labels: ${INCIDENT_LABEL}`,
    "---",
    "",
    "**What happened**",
    "",
    "",
    "**When it was first noticed, and how** (an alert, a person on the floor, the dashboard)",
    "",
    "",
    "**What the appliance was running** (the commit on `main` at the time; the dashboard shows the",
    "flow hash the appliance last reported)",
    "",
    "",
    "**What was done**",
    "",
    "",
    "**What should change** (a pull request here, a wiki page, or nothing)",
    "",
  ].join("\n");
  const created = await forgeApi(cfg, "POST", `/repos/${FORGE_ORGANISATION}/${name}/contents/${INCIDENT_TEMPLATE_PATH}`, {
    content: btoa(String.fromCharCode(...new TextEncoder().encode(template))),
    message: "Add the incident template",
    branch: "main",
  });
  if (!created.ok) throw await refused(`could not commit '${INCIDENT_TEMPLATE_PATH}' to '${name}'`, created);
  console.log(`forge: '${name}' carries the incident template`);
}

/**
 * Protect `main`: no direct pushes, one approval from `administrators` before a merge.
 * `enable_push: false` is what makes "deploy only what is committed" mean "deploy only what was
 * reviewed"; merging stays allowed to anyone with write once approvals are met, so a manager can
 * merge after an administrator approves. `dismiss_stale_approvals` means a change pushed after
 * approval needs approving again. Applied once: an existing protection is left as an administrator
 * may have tuned it.
 */
async function ensureBranchProtection(cfg: ForgeConfig, name: string): Promise<void> {
  const existing = await forgeApi(cfg, "GET", `/repos/${FORGE_ORGANISATION}/${name}/branch_protections/main`);
  if (existing.ok) return;
  if (existing.status !== 404) {
    throw await refused(`could not read the branch protection on '${name}'`, existing);
  }
  // THE LAST MOMENT ANYTHING CAN BE COMMITTED TO `main` DIRECTLY. The protection below binds the
  // machine account too, so what the repository is to carry from the start goes in here, first.
  await seedIssueTemplate(cfg, name);
  const created = await forgeApi(cfg, "POST", `/repos/${FORGE_ORGANISATION}/${name}/branch_protections`, {
    branch_name: "main",
    enable_push: false,
    enable_approvals_whitelist: true,
    approvals_whitelist_teams: [FORGE_TEAMS.Administrator],
    required_approvals: 1,
    block_on_rejected_reviews: true,
    dismiss_stale_approvals: true,
  });
  if (!created.ok) throw await refused(`could not protect 'main' on '${name}'`, created);
}

/**
 * Attach the appliance's public key to its repository, read-only. Titled by sparkplug_id so
 * revocation has an obvious target.
 */
async function ensureDeployKey(
  cfg: ForgeConfig,
  repo: string,
  sparkplugId: string,
  publicKey: string,
): Promise<void> {
  const response = await forgeApi(cfg, "POST", `/repos/${FORGE_ORGANISATION}/${repo}/keys`, {
    title: `gateway ${sparkplugId}`,
    key: publicKey,
    // NEVER false. See the header: a writable key lets an appliance author what it will later be
    // asked to deploy.
    read_only: true,
  });

  if (response.ok) return;

  // 422 is "this key is already registered", which is what re-enrolling an appliance that kept its
  // /data volume looks like. That is a success: the key it holds is the key the repository trusts.
  if (response.status === 422) {
    console.log(`deploy key for ${sparkplugId} was already registered on '${repo}'`);
    return;
  }

  throw await refused(`could not register the deploy key on '${repo}'`, response);
}

/**
 * Seed the wiki's Home page, once. The wiki is the unreviewed half of the repository: a second git
 * repository edited in place by anyone in either team, for what a person needs to know about a
 * gateway and the appliance never reads. A Home page that exists is left as people have edited it;
 * Gitea answers 400 to a second creation.
 */
async function ensureWikiHome(
  cfg: ForgeConfig,
  name: string,
  sparkplugId: string,
  gatewayName: string,
): Promise<void> {
  const existing = await forgeApi(cfg, "GET", `/repos/${FORGE_ORGANISATION}/${name}/wiki/page/Home`);
  if (existing.ok) return;
  if (existing.status !== 404) throw await refused(`could not read the wiki of '${name}'`, existing);

  const content = [
    `# ${gatewayName}`,
    "",
    `Gateway \`${sparkplugId}\`, enrolled ${new Date().toISOString().slice(0, 10)}.`,
    "",
    "This wiki is for what a person needs to know about this gateway and the appliance never reads:",
    "where it is, what it is wired to, who to call, what changed and why. Pages here are edited",
    "directly and are not reviewed.",
    "",
    "The repository beside it is the reverse. `flows.json` there is what the appliance deploys,",
    "`main` is protected, and a change to it goes through a pull request that an administrator",
    "approves. Nothing the appliance deploys belongs in this wiki.",
    "",
  ].join("\n");
  const created = await forgeApi(cfg, "POST", `/repos/${FORGE_ORGANISATION}/${name}/wiki/new`, {
    title: "Home",
    content_base64: btoa(String.fromCharCode(...new TextEncoder().encode(content))),
    message: `Seed the wiki for gateway ${sparkplugId}`,
  });
  if (!created.ok) throw await refused(`could not seed the wiki of '${name}'`, created);
  console.log(`forge: seeded the wiki of '${name}'`);
}

/**
 * Register the push webhook on the repository, once. One hook per repository rather than one on the
 * organisation, because only a gateway's repository has a gateway row to record on. Found again by
 * URL on re-enrolment. The secret is the one forge-events verifies with. `branch_filter: main` so
 * pushes to a proposal branch are not delivered.
 */
async function ensureWebhook(cfg: ForgeConfig, name: string): Promise<void> {
  if (!cfg.webhookUrl) {
    console.log(`forge: no webhook configured, so '${name}' will not report its pushes`);
    return;
  }
  const listed = await forgeApi(cfg, "GET", `/repos/${FORGE_ORGANISATION}/${name}/hooks`);
  if (!listed.ok) throw await refused(`could not list the hooks on '${name}'`, listed);
  const hooks = await listed.json() as { id: number; config?: { url?: string } }[];
  if (hooks.some((h) => h.config?.url === cfg.webhookUrl)) return;

  const created = await forgeApi(cfg, "POST", `/repos/${FORGE_ORGANISATION}/${name}/hooks`, {
    type: "gitea",
    active: true,
    events: ["push"],
    branch_filter: "main",
    config: { url: cfg.webhookUrl, content_type: "json", secret: cfg.webhookSecret },
  });
  if (!created.ok) throw await refused(`could not register the push webhook on '${name}'`, created);
  console.log(`forge: '${name}' reports its pushes to ${cfg.webhookUrl}`);
}

/** Provision the organisation, the repository, its protection and the key. Returns null on any failure, having logged it. */
export async function provisionGatewayRepository(
  cfg: ForgeConfig,
  sparkplugId: string,
  gatewayName: string,
  publicKey: string,
): Promise<ForgeRepository | null> {
  const name = repositoryNameFor(sparkplugId);
  try {
    await ensureOrganisation(cfg);
    const repo = await ensureRepository(cfg, name, gatewayName);
    await ensureBranchProtection(cfg, name);
    await ensureDeployKey(cfg, name, sparkplugId, publicKey);
    console.log(`forge: ${sparkplugId} reads ${repo.full_name} over ${repo.ssh_url}`);
    // After the key, and not on the path to `return null`: a wiki the forge could not seed costs a
    // log line, never the repository the appliance is about to clone.
    try {
      await ensureWikiHome(cfg, name, sparkplugId, gatewayName);
    } catch (err) {
      console.warn(`forge: the wiki of '${name}' was not seeded (${err instanceof Error ? err.message : err}); the repository is unaffected`);
    }
    // LIKEWISE the webhook: it is how the dashboard learns of a push before the appliance's next
    // tick, and a repository without it is a repository the dashboard learns about one tick late.
    try {
      await ensureWebhook(cfg, name);
    } catch (err) {
      console.warn(`forge: the push webhook on '${name}' was not registered (${err instanceof Error ? err.message : err}); the repository is unaffected`);
    }
    return repo;
  } catch (err) {
    // LOUD, because nothing else will say so. The appliance sees `repository: null` and carries on
    // publishing telemetry; without this line the only symptom is a gateway that never converges.
    console.error(
      `forge provisioning FAILED for ${sparkplugId} ` +
        `(${err instanceof Error ? err.message : err}). The gateway is enrolled and its broker ` +
        "credential is live; it has no repository to pull from and will not converge until one exists.",
    );
    return null;
  }
}

/** How long to wait for the forge's asset. Short: enrolment is a person standing at an appliance. */
const HOST_KEY_TIMEOUT_MS = 5000;

/**
 * The `known_hosts` host specification for an SSH URL. OpenSSH matches a non-default port only as
 * `[host]:port` and port 22 only as a bare `host`. Gitea gives `ssh://git@host:2222/owner/repo.git`
 * when SSH_PORT is not 22 and the scp-like `git@host:owner/repo.git` when it is.
 */
export function knownHostsHost(sshUrl: string): string | null {
  const url = sshUrl.trim();

  const withScheme = /^ssh:\/\/(?:[^@/]+@)?([^/:]+)(?::(\d+))?(?:\/|$)/.exec(url);
  if (withScheme) {
    const host = withScheme[1];
    const port = withScheme[2];
    return port && port !== "22" ? `[${host}]:${port}` : host;
  }

  // Any other scheme is refused rather than parsed: the scp-like pattern below would accept
  // `https://forge/x.git` and yield the host `https`, which would be written into known_hosts as a
  // line that can never match.
  if (/^[a-z][a-z0-9+.-]*:\/\//i.test(url)) return null;

  // scp-like: user@host:path. The colon here separates the PATH, never a port -- `git@host:2222/x`
  // means the directory `2222/x` to ssh, not a port, which is why this does not try to read one.
  const scpLike = /^(?:[^@/]+@)?([^/:]+):/.exec(url);
  if (scpLike) return scpLike[1];

  return null;
}

/**
 * Fetch the forge's published SSH host key and return the `known_hosts` line for this repository.
 * Null rather than throwing, and non-fatal like the rest of this file. Shape-checked through
 * `validPublicKey` before it is trusted, so an HTML error page or a truncated read is never written
 * into an appliance's known_hosts. The comment field is dropped: OpenSSH ignores it.
 */
export async function forgeKnownHosts(
  cfg: ForgeConfig,
  sshUrl: string,
): Promise<string | null> {
  const host = knownHostsHost(sshUrl);
  if (!host) {
    console.error(`could not read a host out of the forge's clone URL '${sshUrl}'`);
    return null;
  }

  try {
    const response = await fetch(`${cfg.baseUrl}/assets/ssh_host_key.pub`, {
      signal: AbortSignal.timeout(HOST_KEY_TIMEOUT_MS),
    });
    if (!response.ok) {
      console.error(
        `the forge published no SSH host key (${response.status} from /assets/ssh_host_key.pub). ` +
          "gitea-init.sh publishes it on boot; a forge that has never restarted since this was " +
          "added will not have one yet.",
      );
      return null;
    }

    const key = validPublicKey((await response.text()).trim());
    if (!key) {
      console.error(
        "the forge's /assets/ssh_host_key.pub did not contain an SSH public key. Refusing to hand " +
          "an appliance a known_hosts entry built from it.",
      );
      return null;
    }

    const [algorithm, material] = key.split(/\s+/);
    return `${host} ${algorithm} ${material}`;
  } catch (err) {
    console.error(
      `could not read the forge's SSH host key (${err instanceof Error ? err.message : err}). ` +
        "The gateway will enrol and publish telemetry; it will not converge until it has one.",
    );
    return null;
  }
}
