/**
 * The forge: a gateway's own repository, the key it reads it with, and the branch a proposed flow
 * lands on.
 *
 * SHARED BECAUSE THE REPOSITORY NAME MUST AGREE. `enroll-gateway` creates `gateway-<sparkplug_id>`
 * and `propose-gateway-flow` commits into it; two copies of that convention are two places for it
 * to drift, and the failure is a proposal opened against a repository that does not exist -- or,
 * worse, against one belonging to a different gateway. See _shared/roles.ts on why a sibling import
 * is fine: `servicePath` decides which directory is BOOTED, not what its module graph may import.
 *
 * WHY THIS LIVES BESIDE THE BROKER CREDENTIAL rather than in a later step somebody runs. Roadmap 7
 * gives every appliance a per-gateway READ-ONLY deploy key, and enrolment is the one moment when a
 * gateway is provably itself: it holds a single-use token bound to exactly one row. A key issued
 * later would need some other proof of identity, which is the fleet-wide credential store this
 * architecture exists to avoid.
 *
 * -------------------------------------------------------------------------------------------------
 * THE PRIVATE KEY IS NEVER SEEN HERE, AND THAT IS THE WHOLE SHAPE OF IT.
 *
 * The appliance generates its own keypair in bootstrap.mjs and sends the PUBLIC half up with its
 * enrolment request; this function registers that half against the repository. Nothing secret
 * travels toward the plant, nothing secret is stored here, and revoking one gateway is deleting one
 * key from one repository. It is the same decision as the editor password bootstrap generates and
 * prints once, one credential plane along.
 *
 * READ-ONLY, ALWAYS. A writable deploy key lets an appliance author the flow it will later be asked
 * to deploy, which empties the review step of its meaning -- an approved commit would no longer be
 * evidence that a person approved anything.
 *
 * -------------------------------------------------------------------------------------------------
 * FAILURE HERE IS NON-FATAL, DELIBERATELY, and it is the opposite decision from the credential
 * service's.
 *
 * By the time this runs the token is spent and the broker credential exists. Refusing the enrolment
 * would leave a working broker account no bundle can claim, to punish an appliance for a forge
 * outage it did not cause -- and telemetry, which is what a gateway is FOR, needs nothing from the
 * forge. So a failure is logged loudly, `repository` comes back null, and the appliance enrols
 * without one. What must never happen is silence: the response says so, and the log names the
 * gateway.
 */

export interface ForgeConfig {
  baseUrl: string;
  user: string;
  password: string;
}

export interface ForgeRepository {
  full_name: string;
  ssh_url: string;
  default_branch: string;
}

/**
 * The forge's configuration, or null when this deployment has none.
 *
 * ALL THREE OR NOTHING. A half-configured forge is the case worth being loud about: it looks
 * enabled and answers 401 on every enrolment, so it is reported here rather than discovered one
 * appliance at a time.
 */
export function forgeConfig(): ForgeConfig | null {
  const baseUrl = (Deno.env.get("GITEA_INTERNAL_URL") ?? "").replace(/\/+$/, "");
  const user = Deno.env.get("GITEA_MACHINE_USER") ?? "";
  const password = Deno.env.get("GITEA_MACHINE_PASSWORD") ?? "";

  if (!baseUrl && !user && !password) return null;

  if (!baseUrl || !user || !password) {
    const missing = [
      !baseUrl && "GITEA_INTERNAL_URL",
      !user && "GITEA_MACHINE_USER",
      !password && "GITEA_MACHINE_PASSWORD",
    ].filter(Boolean).join(", ");
    console.error(
      `the forge is half-configured (${missing} unset), so gateway repositories are DISABLED. ` +
        "Set all three or none -- a partially configured forge answers 401 on every enrolment.",
    );
    return null;
  }

  return { baseUrl, user, password };
}

/**
 * The repository name for a gateway.
 *
 * DERIVED, NOT STORED, and that is a decision worth stating: roadmap 9 owns where a repository
 * pointer lives -- a tag on the links store, most likely -- and has not landed. Deriving the name
 * from the `sparkplug_id` needs no column and no migration, and it cannot disagree with the gateway
 * it belongs to: that id is generated by the database, and mosquitto.acl already matches the
 * topic's edge-node segment against it.
 */
export function repositoryNameFor(sparkplugId: string): string {
  return `gateway-${sparkplugId}`;
}

/**
 * The public half of an OpenSSH key, or null.
 *
 * SHAPE-CHECKED HERE so a malformed value never reaches the forge, and CONFINED to the two
 * algorithms bootstrap.mjs can generate. Forwarding whatever arrived would make this endpoint a way
 * to write arbitrary strings into another system's authorised-keys list.
 */
export function validPublicKey(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const key = value.trim();
  if (key.length > 4096) return null;
  return /^ssh-(ed25519|rsa) [A-Za-z0-9+/=]+( [^\n\r]*)?$/.test(key) ? key : null;
}

/** Basic auth as the machine account. Gitea accepts it on the API, and it needs no token exchange. */
function authHeader(cfg: ForgeConfig): string {
  return `Basic ${btoa(`${cfg.user}:${cfg.password}`)}`;
}

/**
 * Create the gateway's repository, or return the one that is already there.
 *
 * `auto_init` MATTERS. An empty repository has no branch, and a deploy key against a repository with
 * no default branch gives the appliance nothing to clone -- git reports "remote HEAD refers to a
 * nonexistent ref", which reads as a broken key rather than as an empty repository.
 */
async function ensureRepository(
  cfg: ForgeConfig,
  name: string,
  gatewayName: string,
): Promise<ForgeRepository> {
  const created = await fetch(`${cfg.baseUrl}/api/v1/user/repos`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: authHeader(cfg) },
    body: JSON.stringify({
      name,
      description: `Node-RED flow for gateway '${gatewayName}'. Managed by ACS-Cymru.`,
      // Belt and braces: the forge sets FORCE_PRIVATE, so a public repository cannot be created
      // here even by mistake. Asking for private anyway means the intent is in the request rather
      // than only in the server's configuration.
      private: true,
      auto_init: true,
      default_branch: "main",
    }),
  });

  if (created.ok) {
    return await created.json() as ForgeRepository;
  }

  // 409 IS THE ORDINARY STATE OF A RE-ENROLMENT, and the repository outliving the appliance is the
  // point rather than an accident: a gateway re-flashed after a failed SD card gets its flow history
  // back, which is the whole reason the flow is in a repository instead of on the appliance.
  if (created.status === 409) {
    const existing = await fetch(`${cfg.baseUrl}/api/v1/repos/${cfg.user}/${name}`, {
      headers: { Authorization: authHeader(cfg) },
    });
    if (!existing.ok) {
      throw new Error(`repository '${name}' exists but could not be read (${existing.status})`);
    }
    return await existing.json() as ForgeRepository;
  }

  throw new Error(
    `could not create repository '${name}' ` +
      `(${created.status}: ${(await created.text()).slice(0, 200)})`,
  );
}

/**
 * Attach the appliance's public key to its repository, read-only.
 *
 * TITLED BY sparkplug_id, so a human reading a repository's key list can tell which appliance holds
 * it and revocation has an obvious target.
 */
async function ensureDeployKey(
  cfg: ForgeConfig,
  repo: string,
  sparkplugId: string,
  publicKey: string,
): Promise<void> {
  const response = await fetch(`${cfg.baseUrl}/api/v1/repos/${cfg.user}/${repo}/keys`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: authHeader(cfg) },
    body: JSON.stringify({
      title: `gateway ${sparkplugId}`,
      key: publicKey,
      // NEVER false. See the header: a writable key lets an appliance author what it will later be
      // asked to deploy.
      read_only: true,
    }),
  });

  if (response.ok) return;

  // 422 is "this key is already registered", which is what re-enrolling an appliance that kept its
  // /data volume looks like. That is a success: the key it holds is the key the repository trusts.
  if (response.status === 422) {
    console.log(`deploy key for ${sparkplugId} was already registered on '${repo}'`);
    return;
  }

  throw new Error(
    `could not register the deploy key on '${repo}' ` +
      `(${response.status}: ${(await response.text()).slice(0, 200)})`,
  );
}

/** Provision the repository and the key. Returns null on any failure, having logged it. */
export async function provisionGatewayRepository(
  cfg: ForgeConfig,
  sparkplugId: string,
  gatewayName: string,
  publicKey: string,
): Promise<ForgeRepository | null> {
  const name = repositoryNameFor(sparkplugId);
  try {
    const repo = await ensureRepository(cfg, name, gatewayName);
    await ensureDeployKey(cfg, name, sparkplugId, publicKey);
    console.log(`forge: ${sparkplugId} reads ${repo.full_name} over ${repo.ssh_url}`);
    return repo;
  } catch (err) {
    // LOUD, because nothing else will say so. The appliance sees `repository: null` and carries on
    // publishing telemetry; without this line the only symptom is a gateway that never converges.
    console.error(
      `forge provisioning FAILED for ${sparkplugId} ` +
        `(${err instanceof Error ? err.message : err}). The gateway is enrolled and its broker ` +
        "credential is live; it has no repository to pull from and will not converge until one exists.",
    );
    return null;
  }
}

/**
 * THE PROPOSAL HALF: a flow becomes a branch and a pull request, never a direct write to `main`.
 *
 * WHY A BRANCH AND NOT A COMMIT ON main. Roadmap 7's three states are the forge's own: an open pull
 * request IS "pending approval", a merge IS "approved", and a revert commit IS "undo". Committing
 * straight to `main` would collapse all three into "deployed", and the appliance -- which converges
 * to whatever `main` says -- would deploy an unreviewed flow the moment somebody pressed Upload.
 * That is the `deploy-nodered` endpoint this item retired, rebuilt with a nicer table.
 *
 * THE PROPOSER IS NAMED IN THE COMMIT AND IN THE PULL REQUEST, because the forge cannot know them:
 * every write here is made by ONE machine account, and shopfloor people deliberately hold no login.
 * Without the name in the message the audit trail says only that the platform committed something.
 * Migration `0089` made the same decision for the approvals queue, and for the same reason.
 */

/** The file every gateway repository holds, and the only one this writes. */
export const FLOW_PATH = "flows.json";

export interface ProposedFlow {
  number: number;
  html_url: string;
  branch: string;
}

/** What a repository currently holds at `flows.json`, or null when it has none yet. */
async function currentFlowSha(cfg: ForgeConfig, repo: string): Promise<string | null> {
  const response = await fetch(
    `${cfg.baseUrl}/api/v1/repos/${cfg.user}/${repo}/contents/${FLOW_PATH}`,
    { headers: { Authorization: authHeader(cfg) } },
  );
  if (response.status === 404) return null;
  if (!response.ok) {
    throw new Error(`could not read ${FLOW_PATH} in '${repo}' (${response.status})`);
  }
  const body = await response.json() as { sha?: string };
  return typeof body.sha === "string" ? body.sha : null;
}

/**
 * Commit a flow onto a NEW branch and open a pull request for it.
 *
 * CREATE-OR-UPDATE, decided by whether the file is already there. Gitea's contents API is POST to
 * create and PUT to update, and PUT needs the blob's `sha` -- posting over an existing file answers
 * 422, which reads as a validation error rather than as "this repository already has a flow".
 *
 * `new_branch` DOES THE BRANCHING, so there is no separate ref call to get wrong: the commit lands
 * on a branch created from the base in one request, which also means a failure leaves no orphan
 * branch behind.
 */
export async function proposeFlow(
  cfg: ForgeConfig,
  repo: string,
  flowJson: string,
  proposer: string,
  gatewayName: string,
  baseBranch = "main",
): Promise<ProposedFlow> {
  const stamp = new Date().toISOString().replace(/[:.]/g, "-");
  // Branch names are a forge-visible surface, so nothing from a caller reaches one: the timestamp
  // is generated here and the gateway is identified by the repository the branch lives in.
  const branch = `proposal/${stamp}`;
  const message =
    `Proposed flow for '${gatewayName}'\n\nProposed by ${proposer} through the ACS-Cymru dashboard.`;

  const sha = await currentFlowSha(cfg, repo);
  const contents = await fetch(
    `${cfg.baseUrl}/api/v1/repos/${cfg.user}/${repo}/contents/${FLOW_PATH}`,
    {
      method: sha ? "PUT" : "POST",
      headers: { "Content-Type": "application/json", Authorization: authHeader(cfg) },
      body: JSON.stringify({
        content: btoa(unescape(encodeURIComponent(flowJson))),
        message,
        branch: baseBranch,
        new_branch: branch,
        ...(sha ? { sha } : {}),
      }),
    },
  );

  if (!contents.ok) {
    throw new Error(
      `could not commit ${FLOW_PATH} to '${repo}' ` +
        `(${contents.status}: ${(await contents.text()).slice(0, 200)})`,
    );
  }

  const pull = await fetch(`${cfg.baseUrl}/api/v1/repos/${cfg.user}/${repo}/pulls`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: authHeader(cfg) },
    body: JSON.stringify({
      head: branch,
      base: baseBranch,
      title: `Flow proposed for '${gatewayName}'`,
      body:
        `Proposed by **${proposer}** through the ACS-Cymru dashboard.\n\n` +
        "Merging this deploys it: the appliance converges to whatever `main` holds. " +
        "Review the diff before approving.",
    }),
  });

  if (!pull.ok) {
    // THE BRANCH SURVIVES A FAILED PULL REQUEST, deliberately. The commit is already made and is the
    // thing worth keeping; a proposer can open the request by hand, and deleting the branch to tidy
    // up would throw away the only copy of what they uploaded.
    throw new Error(
      `committed ${FLOW_PATH} to '${branch}' but could not open a pull request ` +
        `(${pull.status}: ${(await pull.text()).slice(0, 200)})`,
    );
  }

  const opened = await pull.json() as { number: number; html_url: string };
  return { number: opened.number, html_url: opened.html_url, branch };
}

/**
 * =================================================================================================
 * THE FORGE'S OWN IDENTITY, so an appliance can verify it rather than trust it on sight.
 * =================================================================================================
 *
 * WHAT THIS CLOSES. A gateway clones over SSH with its deploy key. Without a `known_hosts` entry it
 * has two options and both are wrong: accept whatever key answers on the first connection, which is
 * trust-on-first-use and puts the whole of the trust decision at the one moment an attacker would
 * choose; or be told to skip verification, which roadmap 7 and 11 both refuse outright and which
 * would quietly become the way every appliance is configured. An appliance that pulls unattended for
 * years is the worst possible holder of an unverified host key.
 *
 * WHY THE ANSWER TRAVELS THROUGH THE ENROLMENT RESPONSE. The appliance is already talking to the
 * platform over TLS, holding a single-use token bound to exactly one gateway row -- the one moment
 * it is provably itself, and the same reason the deploy key is registered here rather than later.
 * Handing it the forge's host key on that channel means it knows the forge's identity BEFORE its
 * first clone. Nothing in the bundle fetches this URL directly: an appliance that did would be
 * trusting the network again, which is the thing being removed.
 *
 * THE KEY IS PUBLIC AND ITS SECRECY IS NOT THE POINT. Anyone who can reach port 22 is handed it
 * during the handshake -- `ssh-keyscan` is precisely that. What the platform supplies is not
 * confidentiality but ATTESTATION: *this* is the key the forge you were told to use presents.
 *
 * SERVED BY GITEA ITSELF, from `custom/public/`, which it publishes at `/assets/`. `gitea-init.sh`
 * copies the `.pub` there on every boot, so a rotated host key republishes itself. Read here over
 * `GITEA_INTERNAL_URL`, which is the same internal path the machine account already authenticates
 * on -- no new credential, no new route, and no new place for the forge's address to be configured.
 */

/** How long to wait for the forge's asset. Short: enrolment is a person standing at an appliance. */
const HOST_KEY_TIMEOUT_MS = 5000;

/**
 * The `known_hosts` host specification for an SSH URL.
 *
 * THE BRACKET FORM IS NOT COSMETIC. OpenSSH writes a non-default port as `[host]:port` and matches
 * on exactly that string; a bare `host` line is simply not consulted for a connection to port 2222,
 * and the appliance is then told the host is unknown while holding a file that names it. Port 22 is
 * the opposite case -- it must be bare, because that is what OpenSSH looks up.
 *
 * Gitea gives `ssh://git@host:2222/owner/repo.git` when SSH_PORT is not 22 and the scp-like
 * `git@host:owner/repo.git` when it is, so both spellings arrive here and neither is a fault.
 */
export function knownHostsHost(sshUrl: string): string | null {
  const url = sshUrl.trim();

  const withScheme = /^ssh:\/\/(?:[^@/]+@)?([^/:]+)(?::(\d+))?(?:\/|$)/.exec(url);
  if (withScheme) {
    const host = withScheme[1];
    const port = withScheme[2];
    return port && port !== "22" ? `[${host}]:${port}` : host;
  }

  // ANY OTHER SCHEME IS REFUSED RATHER THAN PARSED, and this branch exists because the scp-like
  // pattern below silently accepts one: `https://forge/x.git` matches it and yields the "host"
  // `https`, which would be written into an appliance's known_hosts as a line that can never match.
  // The appliance would then fail verification against a file that names the forge, which is the
  // most confusing failure this whole path could produce. Caught by test rather than by reading.
  if (/^[a-z][a-z0-9+.-]*:\/\//i.test(url)) return null;

  // scp-like: user@host:path. The colon here separates the PATH, never a port -- `git@host:2222/x`
  // means the directory `2222/x` to ssh, not a port, which is why this does not try to read one.
  const scpLike = /^(?:[^@/]+@)?([^/:]+):/.exec(url);
  if (scpLike) return scpLike[1];

  return null;
}

/**
 * Fetch the forge's published SSH host key and return the `known_hosts` line for this repository.
 *
 * NULL RATHER THAN THROWING, and non-fatal for the same reason the rest of this file is: by the time
 * enrolment reaches here the token is spent and the broker credential is live. An appliance that
 * gets no host key still publishes telemetry, which is what a gateway is FOR -- it simply declines
 * to converge, which is the correct refusal rather than a degraded one.
 *
 * SHAPE-CHECKED BEFORE IT IS TRUSTED. `validPublicKey` is the same gate the appliance's own key
 * passes through, and it is what stops an HTML error page, a login redirect or a truncated read
 * being written into an appliance's known_hosts as though it were a key. The comment field is
 * dropped: OpenSSH ignores it and it carries the forge container's hostname, which is noise on an
 * appliance and one more thing that changes for no reason.
 */
export async function forgeKnownHosts(
  cfg: ForgeConfig,
  sshUrl: string,
): Promise<string | null> {
  const host = knownHostsHost(sshUrl);
  if (!host) {
    console.error(`could not read a host out of the forge's clone URL '${sshUrl}'`);
    return null;
  }

  try {
    const response = await fetch(`${cfg.baseUrl}/assets/ssh_host_key.pub`, {
      signal: AbortSignal.timeout(HOST_KEY_TIMEOUT_MS),
    });
    if (!response.ok) {
      console.error(
        `the forge published no SSH host key (${response.status} from /assets/ssh_host_key.pub). ` +
          "gitea-init.sh publishes it on boot; a forge that has never restarted since this was " +
          "added will not have one yet.",
      );
      return null;
    }

    const key = validPublicKey((await response.text()).trim());
    if (!key) {
      console.error(
        "the forge's /assets/ssh_host_key.pub did not contain an SSH public key. Refusing to hand " +
          "an appliance a known_hosts entry built from it.",
      );
      return null;
    }

    const [algorithm, material] = key.split(/\s+/);
    return `${host} ${algorithm} ${material}`;
  } catch (err) {
    console.error(
      `could not read the forge's SSH host key (${err instanceof Error ? err.message : err}). ` +
        "The gateway will enrol and publish telemetry; it will not converge until it has one.",
    );
    return null;
  }
}
