apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: timescaledb
    type: postgres
    access: proxy
    url: timescaledb:5432
    user: postgres
    database: postgres
    isDefault: true
    version: 2
    secureJsonData:
      password: postgres
    jsonData:
      database: postgres
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true

  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false