-- Migration: 20260101000016_metric_group.sql
-- Description: Derive a top-level group from each catalog metric's path-style name, so a growing
-- catalog can be navigated by category ("Axes/C/ANGULAR_VELOCITY" -> "Axes") instead of as one
-- flat alphabetical list.
--
-- The separator is '/', not '.', because that is what everything this platform interoperates with
-- already uses for exactly this purpose:
--   * Sparkplug B's own reserved metric names are path-style -- "Node Control/Rebirth",
--     "Properties/Hardware Make".
--   * Factory+ (which this platform claims alignment with) requires metric name segments to be
--     alphanumeric-and-underscore only, and expresses hierarchy as folders: a metric "Foo" may not
--     coexist with a folder "Foo/Bar". A '.' is not a legal character in a Factory+ metric name.
--   * MTConnect identifies an observation by component path plus data item type, which composes
--     the same way: "Axes/C/ANGULAR_VELOCITY/ACTUAL".
-- Metric names are immutable once created, so this had to be settled before any were issued.
--
-- The group lives *in the name*, not in a column of its own, and this is derived from it. That is
-- deliberate: the name is the wire contract, so a name-carried group is visible everywhere the
-- metric is -- raw MQTT, telemetry.metric_name in TimescaleDB, and Grafana, which queries
-- TimescaleDB directly and can never see a Supabase-side category column. A separate editable
-- category column would be free to recategorise but invisible to every consumer outside Supabase.
--
-- GENERATED ALWAYS ... STORED, matching the sparkplug_id pattern (migration 0014): the group
-- cannot drift from the name it is derived from, and needs no trigger to keep it honest. The
-- existing enforce_metric_catalog_immutability() trigger already makes `name` immutable, so in
-- practice a metric's group is immutable too -- recategorising means deprecating the entry and
-- adding a new one, exactly as renaming does. That is the correct cost for a change that alters
-- what a physical device must publish.
--
-- Deliberately NOT constrained: no CHECK requires a separator. The starter catalog seeded by
-- migration 0013 is flat (`temperature`, `availability`, ...) and those names are immutable and
-- already published by the simulator, so a hard constraint would make this migration unappliable.
-- A name with no separator yields NULL -- "ungrouped" -- which the UI renders as its own section.
-- The convention is encouraged in the Add Metric form, not enforced in the schema.
--
-- NULL rather than a literal 'Ungrouped': an absent group is absent, and when device tagging is
-- derived from these groups a NULL naturally contributes no tag rather than a tag named after the
-- absence of one.

-- supabase-db-init replays every migration on each stack start, and ADD COLUMN IF NOT EXISTS is a
-- no-op against a column that already exists -- including one generated by an *earlier revision of
-- this file*, which used '.'. That would leave a database silently deriving groups the wrong way
-- while the file said otherwise. Drop the stale column so the definition below is what actually
-- takes effect. Safe: the column is generated, so nothing is lost by rebuilding it.
DO $$
DECLARE
  current_expression TEXT;
BEGIN
  SELECT generation_expression INTO current_expression
    FROM information_schema.columns
   WHERE table_schema = 'public'
     AND table_name = 'metric_catalog'
     AND column_name = 'metric_group';

  IF current_expression IS NOT NULL AND current_expression NOT LIKE '%/%' THEN
    RAISE NOTICE 'Rebuilding metric_catalog.metric_group: stored expression predates the / separator';
    ALTER TABLE public.metric_catalog DROP COLUMN metric_group;
  END IF;
END
$$;

ALTER TABLE public.metric_catalog
  ADD COLUMN IF NOT EXISTS metric_group TEXT
  GENERATED ALWAYS AS (
    -- strpos guard: without it a flat name would become its own group. NULLIF catches a name
    -- that merely *starts* with the separator, whose first segment is the empty string.
    CASE WHEN strpos(name, '/') > 0 THEN NULLIF(split_part(name, '/', 1), '') END
  ) STORED;

CREATE INDEX IF NOT EXISTS idx_metric_catalog_group ON public.metric_catalog (metric_group);

NOTIFY pgrst, 'reload schema';
